version: '3.9'
services:
  frontend:
    build: ./frontend
    ports:
      - "8080:3000"
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - PYTHONUNBUFFERED=1